# This is the main configuration file of DiSky.
# Made for v4, older configuration version won't work.

# In the DiSky error handler, which error code should not be shown in the console?
# You can take a took at every discord error code here:
# https://discord.com/developers/docs/topics/opcodes-and-status-codes#json
ignored-core:
  - '50006' # Hide empty message error

# Debug is disabled by default.
# If an admin or a developer wants to debug the bot, enable this option.
# Debug messages will be sent to the console, and the bot will be restarted.
debug: false

# Enable or not the 'token of %bot' expression.
# It's mainly to avoid others people that have access to Skript to get the token.
# Restart needed to take effect.
token-of-bot-expression: true